# Generated by Django 4.2.5 on 2023-09-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.TextField(max_length=500)),
                ('name', models.TextField(max_length=500)),
                ('company', models.TextField(max_length=500)),
                ('price', models.BigIntegerField()),
                ('image', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('category', models.TextField(max_length=500)),
                ('featured', models.BooleanField(default=True)),
            ],
        ),
    ]
