# Generated by Django 4.2.5 on 2023-09-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ids',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.TextField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
